twitter:
  host: "api.twitter.com"
  #port: "443"
  basePath: "1.1/favorites"
  path: "create.json"
  
oauth:
  method: "POST"
  url: "https://api.twitter.com/1.1/favorites/create.json"
  oauth_nonce: "Au3OgPabtrP"
  oauth_signature_method: "HMAC-SHA1"
  "oauth_version": "1.0"  